import { __apiInternal, api, getBackendHealth } from './apiClient/internal/client';
import { getAuthConfig, getMe, googleAuth, logoutRequest } from './apiClient/endpoints/auth';
import { getAuditLogs } from './apiClient/endpoints/audit';
import {
  analyzeDocument,
  analyzeDocumentJob,
  analyzeFromDiagram,
  analyzeFromDiagramJob,
  analyzeFromUmlCode,
  analyzeFromUmlCodeJob,
  analyzeSystem,
  analyzeSystemJob,
  compareAnalyses,
  deleteAnalysis,
  downloadAnalysisDiagramPng,
  downloadAnalysisPdf,
  extractDiagram,
  getAnalyses,
  getAnalysis,
  getAnalysisDiagramSvg,
  getAnalysisJob,
  getAnalysisSummary,
  getAnalysisVersionComparison,
  getModelReadiness,
} from './apiClient/endpoints/analysis';
import {
  createProject,
  getProject,
  getProjectActivity,
  getProjectAnalyses,
  getProjects,
  updateProject,
} from './apiClient/endpoints/projects';

export {
  __apiInternal,
  analyzeDocument,
  analyzeDocumentJob,
  analyzeFromDiagram,
  analyzeFromDiagramJob,
  analyzeFromUmlCode,
  analyzeFromUmlCodeJob,
  analyzeSystem,
  analyzeSystemJob,
  compareAnalyses,
  createProject,
  deleteAnalysis,
  downloadAnalysisDiagramPng,
  downloadAnalysisPdf,
  extractDiagram,
  getAuditLogs,
  getAnalyses,
  getAnalysis,
  getAnalysisDiagramSvg,
  getAnalysisJob,
  getAnalysisSummary,
  getAnalysisVersionComparison,
  getAuthConfig,
  getBackendHealth,
  getMe,
  getModelReadiness,
  getProject,
  getProjectActivity,
  getProjectAnalyses,
  getProjects,
  googleAuth,
  logoutRequest,
  updateProject,
};

export default api;
