MAX_EXTRACTED_TEXT_LENGTH = 5000

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg"}
MERMAID_EXTENSIONS = {".mmd", ".mermaid"}
PLANTUML_EXTENSIONS = {".puml", ".plantuml", ".uml"}
DRAWIO_EXTENSIONS = {".drawio", ".xml"}
PDF_EXTENSIONS = {".pdf"}
SUPPORTED_EXTENSIONS = (
    IMAGE_EXTENSIONS
    | MERMAID_EXTENSIONS
    | PLANTUML_EXTENSIONS
    | DRAWIO_EXTENSIONS
    | PDF_EXTENSIONS
)
